### PR TITLE
Anywidget Support

### PR DESCRIPTION
**Pull request by koaning**
This PR brings in support for the first widgets supplied by anywidget. There's a bunch of cool things we might do here :)

### CODE REVIEW

**Comment by ogrisel** [comment]
In the `widget.data` dict and the resulting `widget.as_pandas` export, I would fined it more intuitive to get the class name instead of the hexadecimal color code in the third column.

**Comment by ogrisel** [comment]
I tried locally (installed in editable mode) and it seems to work within the jupyter editor of VS Code.

However, I tried to install from the .zip of this github branch from a colab notebook and it complains from a missing .css file:

```python
FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-2-9e9c9dc8bb35>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from drawdata import ScatterWidget
      2 
      3 widget = ScatterWidget()
      4 widget

3 frames

[/usr/local/lib/python3.10/dist-packages/anywidget/_util.py](https://localhost:8080/#) in try_file_contents(x)
    256     path = maybe_path
    257     if not path.is_file():
--> 258         raise FileNotFoundError(f"File not found: {path}")
    259     return FileContents(
    260         path=path,

FileNotFoundError: File not found: /usr/local/lib/python3.10/dist-packages/drawdata/static/scatter_widget.css
```

https://colab.research.google.com/drive/14c_Fju9qi0H1mT8yQ8mnkwicoXU9N6zw?usp=sharing

**Comment by ogrisel** [comment]
I also wanted to try from the jupyterlite install from the scikit-learn website: https://scikit-learn.org/stable/lite/lab/ but there I cannot even install some of the dependencies of `ipywidgets` and `anywidget`:

```python
ValueError: Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0.10'.
```

**Comment by lesteve** [comment]
I think widgets in JupyterLite needs some special setup both at build time and client-side.

Maybe this doc explains it a bit: 
https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html

The reason it works on the ipywidgets repo may be their `jupyterlite_config.json` that adds additional wheels: https://github.com/jupyter-widgets/ipywidgets/blob/main/docs/lite/jupyter_lite_config.json

`micropip` only supports wheels as far as I know hence I would not expect your `.zip` attempt to work.

**Comment by ogrisel** [comment]
Thanks @lesteve!

**Comment by koaning** [comment]
@ogrisel 

> I would fined it more intuitive to get the class name instead of the hexadecimal color code in the third column.

I will add both. The color is useful for plotting libraries later down the line to ensure that you're using the same color. But the classname is supposed to remain intact.

> I also wanted to try from the jupyterlite install from the scikit-learn website

While I agree it is a nice feature, I think it's fine to add jupyterlite support later.

**Comment by koaning** [comment]
@ogrisel I've renamed the `widget.as_pandas` to `widget.data_as_pandas` (same to `widget.data_as_polars` because that feels more fitting as a property. 

Given that final change, any objections to making a release? I still need to make changes to the README but that should be easy enough to do on my own.

**Pull request merged**
